[paths]
codebook = 'none' ### 
psf_file = 'psfs/psf_750_Scope3_final.npy'
#psf_file = 'psfs/dic_psfff_scope6_60X_cy5_300pix.pkl'  ### Scope5 psf
flat_field_tag = 'flat_field/Scope3_'
hyb_range = 'H1_BICAN_set1:H16_BICAN_set1'
hyb_folders = ['Tominersen_Human_05_09_2025']
output_folder = 'MERFISH_Analysis_MERMAKE'
fov_range = '0:1'
#background_range = 'H0_background_set1:H0_background_set1'
#---------------------------------------------------------------------------------------#
#---------------------------------------------------------------------------------------#
#           you probably dont have to change any of the settings below                  #
#---------------------------------------------------------------------------------------#
#---------------------------------------------------------------------------------------#
hyb_save =  '{fov}--{tag}--col{icol}__Xhfits.npz'
dapi_save = '{fov}--{tag}--dapiFeatures.npz'
drift_save = 'drift_{fov}--_set{iset}.pkl'
regex = '''([A-z]+)(\d+)_(.+)_set(\d+)(.*)''' #use triple quotes to avoid double escape

[hybs]
tile_size = 500
overlap = 89
beta = 0.0001
threshold = 3600
blur_radius = 30
delta = 1
delta_fit = 3
sigmaZ = 1
sigmaXY = 1.5


[dapi]
tile_size = 500
overlap = 89
beta = 0.01
threshold = 3.0
blur_radius = 50
delta = 5
delta_fit = 5
sigmaZ = 1
sigmaXY = 1.5
